/**
 * This module was automatically generated by `ts-interface-builder`
 * https://github.com/gristlabs/ts-interface-checker
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AuthState = t.iface([], {
  "token": "string",
  "isAuthenticated": "boolean",
  "loginHasFailed": "boolean",
  "expirationDate": t.opt("Date"),
  "userName": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  AuthState,
};
export default exportedTypeSuite;
