/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const AuthState = t.iface([], {
  token: 'string',
  isAuthenticated: 'boolean',
  loginHasFailed: 'boolean',
  expirationDate: t.opt('Date'),
  userDetails: t.opt('User'),
});

const exportedTypeSuite: t.ITypeSuite = {
  AuthState,
};
export default exportedTypeSuite;
