spring:
   data:
      rest:
         base-path: /api
   jpa:
      properties:
         hibernate:
            show_sql: false
            use_sql_comments: false
            format_sql: false
   h2:
      console:
         enabled: true
logging:
   level:
      org:
         hibernate:
            type: debug
app:
   jwtSecret: PaDeGaInDePeDe
   jwtExpirationInMs: 1800000
pictfam:
   folders: ["/home/jeje/Pictures"]
   users:
      -
         name: jeje
         uid: 1000
         password: $2a$12$.EMYRizBjXa9guzCAarkB.Un9VGJFw9ffohH9xWDbvJDwHXDHxlKC
      -
         name: other
         uid: 1001
         password: $5$8Hj0DXMUCvf$Hlzv/MoDA9AXNyla.3LWXr1v6SqOg90eacn.dPmyPQ6

   
   groups:
      -
         name: group1
         gid: 1000
         users: [1000, 1001]
      -
         name: group2
         gid: 1001
