spring:
   data:
      rest:
         base-path: /api
   jpa:
      properties:
         hibernate:
            show_sql: false
            use_sql_comments: false
            format_sql: false
      hibernate:
         ddl-auto: create
#         ddl-auto: create
      database-platform: org.hibernate.dialect.MariaDB103Dialect
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:mariadb://localhost:3306/pictfam?useLegacyDatetimeCode=false&serverTimezone=UTC
      username: pictfam
      password: pictfam
      driver-class-name: org.mariadb.jdbc.Driver
logging:
   level:
      org:
         hibernate:
            type: info
app:
   jwtSecret: jwtSecretPassword
   jwtExpirationInMs: 1800000
pictfam:
   foldersImages: ["/home/jeje/Pictures/"]  #Path should be without file separator at the end
   foldersVideos: ["/home/jeje/Videos/"]
   users:
      -
         name: jeje
         uid: 1000
         password: jeje
         admin: true
      -
         name: nana
         uid: 1001
         password: nana
         admin: false

   groups:
      -
         name: jeje
         gid: 1002
         users: [1000, 1001]
      -
         name: group1
         gid: 1005
         users: [1000,1001,1003]
